# Netlify configuration (optional but nice to have)

[build]
  # If you add a build step later, set command here
  command = ""
  publish = "frontend"

# Simple SPA fallback
# SPA fallback

# Serve static HTML pages directly (before SPA fallback)
[[redirects]]
  from = "/viewer.html"
  to = "/viewer.html"
  status = 200

[[redirects]]
  from = "/scoreboard.html"
  to = "/scoreboard.html"
  status = 200

[[redirects]]
  from = "/events.html"
  to = "/events.html"
  status = 200

[[redirects]]
  from = "/courts.html"
  to = "/courts.html"
  status = 200

# API proxy to Render
[[redirects]]
  from = "/api/*"
  to = "https://picoscorekeeper.onrender.com/:splat"
  status = 200

# SPA fallback for any other paths
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
