services:
  - type: web
    name: PicoScoreKeeper
    env: python
    rootDirectory: backend
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      # Restrict CORS to your Netlify site once live (comma separated origins)
      # - key: CORS_ALLOW
      #   value: https://picoscorekeeper.netlify.app
